config/routes.rb
ToDoList::Application.routes.draw do

  resources :lists
  root :to => 'lists#index'

  match 'prueba' => 'lists#index', default: {:format => 'js'}

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :est_list, :name_list
  validates_presence_of :name_list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :control_check_cors
  after_filter :control_header_cors

  def control_header_cors
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Max-Age'] = "728000"
  end

  def control_check_cors
    if request.method == :options
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
      headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version'
      headers['Access-Control-Max-Age'] = "728000"
      render :text => '', :content_type => 'jasonp' 
    end
  end


end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @incomplete_lists = List.where(est_list: false)
    @complete_lists = List.where(est_list: true)
  end
  
  def new
    @list = List.new
  end

  def create
   @list = List.create!(params[:list])
   respond_to do |format|
      format.html { redirect_to lists_url}
      format.js {render 'widindex'}
   end
  end

  def update
    @list = List.find(params[:id])
    @list.update_attributes!(params[:list])
    respond_to do |format|
      format.html { redirect_to lists_url}
      format.js
   end
  end

  def destroy
    @list = List.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to lists_url}
      format.js
   end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoList</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list, remote: true do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>
      <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.text_field :name_list %>
  </div>
  <div class="actions">
    <%= f.submit "Crear" %>
  </div>
  
<% end %>

app/views/lists/_list.html.erb
<%= form_for list, remote: true do |f| %>
  <%= f.check_box :est_list %>
  <%= f.submit "Update" %>
  <%= f.label :est_list, list.name_list %>
  <%= link_to "(remove)", list, method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
<% end %>

app/views/lists/create.js.erb
$('#new_list').remove();
$('#new_link').show();
$('#incomplete_lists').append('<%= j render(@list) %>');
$('#edit_list_<%= @list.id %>').submitOnCheck();

app/views/lists/destroy.js.erb
$('#edit_list_<%= @list.id %>').remove();

app/views/lists/index.html.erb
<h2>To Do List</h2>

<%= link_to "New Task", new_list_path, id: "new_link", remote: true %>

<h3>Task to Do</h3>
<div class = "lists" id = "incomplete_lists">
  <%= render @incomplete_lists %>
</div>

<h3>Task Done</h3>
<div class = "lists" id = "complete_lists">
  <%= render @complete_lists %>
</div>

app/views/lists/new.html.erb
<h1>To Do List</h1>

<%= render 'form' %>

app/views/lists/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/lists/update.js.erb
<% if @list.est_list? %>
  $('#edit_list_<%= @list.id %>').appendTo('#complete_lists');
<% else %>
  $('#edit_list_<%= @list.id %>').appendTo('#incomplete_lists');
<% end %>